# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defectdetection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(240, 10, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel { font-size:32px; }")
        self.name.setObjectName("name")
        self.left_label = QtWidgets.QLabel(self.centralwidget)
        self.left_label.setGeometry(QtCore.QRect(110, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.left_label.setFont(font)
        self.left_label.setStyleSheet("QLabel { font-size:16px; }")
        self.left_label.setObjectName("left_label")
        self.right_label = QtWidgets.QLabel(self.centralwidget)
        self.right_label.setGeometry(QtCore.QRect(570, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.right_label.setFont(font)
        self.right_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.right_label.setStyleSheet("QLabel { font-size:16px; }")
        self.right_label.setObjectName("right_label")
        self.button_left = QtWidgets.QPushButton(self.centralwidget)
        self.button_left.setGeometry(QtCore.QRect(290, 500, 181, 34))
        self.button_left.setObjectName("button_left")
        self.img_left = QtWidgets.QLabel(self.centralwidget)
        self.img_left.setGeometry(QtCore.QRect(50, 160, 300, 300))
        self.img_left.setAutoFillBackground(False)
        self.img_left.setStyleSheet("color:rgb(255, 255, 255)")
        self.img_left.setText("")
        self.img_left.setObjectName("img_left")
        self.img_right = QtWidgets.QLabel(self.centralwidget)
        self.img_right.setGeometry(QtCore.QRect(440, 160, 300, 300))
        self.img_right.setStyleSheet("color:rgb(255, 255, 255)")
        self.img_right.setText("")
        self.img_right.setObjectName("img_right")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "缺陷检测"))
        self.name.setText(_translate("MainWindow", "钢铁表面缺陷检测系统"))
        self.left_label.setText(_translate("MainWindow", "待检测的钢铁表面图像"))
        self.right_label.setText(_translate("MainWindow", "检测结果"))
        self.button_left.setText(_translate("MainWindow", "加载并检测图像"))
